const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(rootDir, relativePath), "utf8");
}

function stripCommonJs(source) {
  return source
    .replace(/^const readline = require\("readline"\);\r?\n/m, "")
    .replace(/^const \{ parseDAX \} = require\("\.\/scripts\/daxParser"\);\r?\n/m, "")
    .replace(/^const \{ explainRule \} = require\("\.\/scripts\/explanationEngine"\);\r?\n/m, "")
    .replace(/^const \{ applyTemplate \} = require\("\.\/scripts\/fixEngine"\);\r?\n/m, "")
    .replace(/const rules = loadRules\(\);/, "let rules = [];")
    .replace(/const argDax = process\.argv[\s\S]*?module\.exports = \{[\s\S]*?\};\s*$/m, "");
}

function stripModuleExports(source) {
  return source.replace(/\r?\nif \(typeof module !== "undefined"\) \{[\s\S]*?\r?\n\}\r?\n?$/m, "")
    .replace(/\r?\nmodule\.exports = \{[\s\S]*?\};\s*$/m, "");
}

const parser = stripModuleExports(read("scripts/daxParser.js"));
const explanation = stripModuleExports(read("scripts/explanationEngine.js"));
const fixEngine = stripModuleExports(read("scripts/fixEngine.js"));
const analyzer = stripCommonJs(read("analyze-dax.js"));

const output = `// Generated by scripts/buildBrowserDaxEngine.js. Do not edit directly.
(function () {
  ${parser}

  ${explanation}

  ${fixEngine}

  ${analyzer}

  function setRules(nextRules) {
    rules = Array.isArray(nextRules) ? nextRules : [];
  }

  function analyzeRuleMatches(dax) {
    const parsed = parseDAX(dax);
    const results = rules.map((rule) => {
      const matchScore = scoreMatchParsed(rule, dax, parsed);
      const confidence = matchScore * getRuleConfidence(rule);
      const fix = applyTemplate(rule, parsed);

      return {
        rule,
        parsed,
        issue: rule.pattern,
        explanation: explainRule(rule, parsed),
        fix: fix.fix,
        fix_type: fix.fix_type,
        matchScore,
        finalScore: confidence,
        confidence,
        exactMatch: isExactRuleExample(rule, dax),
        requiresLLM: confidence < LLM_THRESHOLD
      };
    });

    return results
      .filter((result) => result.confidence > LLM_THRESHOLD)
      .sort((a, b) => {
        if (a.exactMatch !== b.exactMatch) return a.exactMatch ? -1 : 1;
        return b.confidence - a.confidence;
      });
  }

  window.PowerBIDaxEngine = {
    analyzeDAX,
    analyzeRuleMatches,
    applyTemplate,
    explainRule,
    formatAnalysisResult,
    matchCondition,
    matchesRule,
    parseDAX,
    scoreMatch,
    setRules
  };
})();
`;

fs.writeFileSync(path.join(rootDir, "src", "daxEngine.js"), output);
